function phpnukeMap()
{var mapCanvas=document.getElementById(feedback_data.mapid);var mapOptions={center:new google.maps.LatLng(feedback_data.lat,feedback_data.lng),mapTypeId:google.maps.MapTypeId.ROADMAP,zoom:feedback_data.zoom,panControl:feedback_data.panControl,zoomControl:feedback_data.zoomControl,zoomControlOptions:{style:google.maps.ZoomControlStyle.DEFAULT},mapTypeControl:feedback_data.mapTypeControl,scaleControl:feedback_data.scaleControl,streetViewControl:feedback_data.streetViewControl,overviewMapControl:feedback_data.overviewMapControl,rotateControl:feedback_data.rotateControl};var map=new google.maps.Map(mapCanvas,mapOptions);var marker=new google.maps.Marker({position:mapOptions.center,icon:feedback_data.marker_icon,animation:google.maps.Animation.BOUNCE});marker.setMap(map);google.maps.event.addListener(marker,'click',function(){var infowindow=new google.maps.InfoWindow({content:feedback_data.infowindow});infowindow.open(map,marker)})}
$(document).ready(function(){$("#feedback_submit").click(function(e)
{$("#feedback_form").validate({submitHandler:function(form){$("#feedback_response").html('<span class="ajax-loader"></span>');var feedback_fields={}
feedback_fields.sender_name=$("#feedback_name").val();feedback_fields.sender_email=$("#feedback_email").val();feedback_fields.subject=$("#feedback_subject").val();feedback_fields.message=$("#feedback_message").val();feedback_fields.security_code=$("#security_code_feedback").val();feedback_fields.feedback_dept=$("#feedback_dept").val();feedback_fields.custom={};$(feedback_data.custom_data).each(function(index,value)
{feedback_fields.custom[value]=$("#feedback_"+value).val()});$.post(phpnuke_url+"index.php?modname=Feedback",{submit:"ok",feedback_fields:feedback_fields},function(response,status)
{response=typeof response==='object'?response:JSON.parse(response);$("#feedback_response").html('<div class="alert alert-'+response.status+' fade in"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>'+response.message+'</div>');e.preventDefault()})}})});$("#reply_feedback_submit").click(function(e)
{var feedback_reply_message=$("#feedback_reply_message").val();var fid=$(this).data("fid");var admin_file=$(this).data("adminfile");$("#reply_feedback_submit").hide();$.post(admin_file+".php",{op:"reply_feedback_pm",fid:fid,submit:"ok",feedback_reply_message:feedback_reply_message},function(response,status)
{response=typeof response==='object'?response:JSON.parse(response);if(response.status=='error')
alert(response.message)
else $(".chat-history").append('<li style="list-style:none;"><div class="message-data"><span class="message-data-name">'+response.sender_name+'</span><span class="message-data-time">'+response.time+'</span><span class="clearfix"></span></div><div class="message my-message align-'+response.direction+'">'+response.message+'</div></li>');e.preventDefault();$("#reply_feedback_submit").show()})})})